name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: macOS Build
      id: mac
      run: |
        cd /Users/runner/work/futurerestore/futurerestore/.github/workflows
        ./mac.sh
    - name: Archive
      id: archive
      uses: actions/upload-artifact@v2
      with:
        name: futurerestore-macOS
        path: |
          /Users/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-*.tar.xz
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "12.0.0"
        force-version: true
        ubuntu-version: "20.04"
        directory: /home/runner/work/futurerestore/futurerestore/.github/llvm
    - name: Symlink LLVM
      if: contains(matrix.os, 'ubuntu')
      run: sudo ln -s libclang-12.so.1 /lib/x86_64-linux-gnu/libclang.so
      working-directory: ${{ env.LLVM_PATH }}/lib
    - name: Ubuntu Build
      id: ubuntu
      run: |
        cd /home/runner/work/futurerestore/futurerestore/.github/workflows
        ./ubuntu.sh
    - name: Archive
      id: archive
      uses: actions/upload-artifact@v2
      with:
        name: futurerestore-Ubuntu
        path: |
          /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-*.tar.xz
